---
- name: Debug
  ansible.builtin.debug:
    msg: Host {{ inventory_hostname }}.

- name: Pass nginx config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf }}"

- name: Pass nginx to kibana proxy config
  ansible.builtin.template:
    src: kibana.conf.j2
    dest: "{{ nginx_confd }}/kibana.conf"

- name: Enable nginx service
  ansible.builtin.systemd:
    name: nginx
    enabled: true
    masked: no

- name: Start nginx service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    daemon_reload: true
