---
- name: Debug
  ansible.builtin.debug:
    msg: Host {{ inventory_hostname }}.

- name: Pass JSON template for rsyslog
  ansible.builtin.copy:
    src: 1-json-template.conf
    dest: "{{ rsyslog_confd }}/1-json-template.conf"
    owner: root
    group: root

- name: Pass config for rsyslog
  ansible.builtin.template:
    src: 2-logstash.conf.j2
    dest: "{{ rsyslog_confd }}/2-logstash.conf"
    owner: root
    group: root

- name: Enable rsyslog service
  ansible.builtin.systemd:
    name: rsyslog
    enabled: true
    masked: no

- name: Start rsyslog service
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted
    daemon_reload: true
