---
- name: Debug
  ansible.builtin.debug:
    msg: Host {{ inventory_hostname }}.

- name: Enable monit service
  ansible.builtin.systemd:
    name: monit
    enabled: true
    masked: no

- name: Start monit service
  ansible.builtin.systemd:
    name: monit
    state: restarted
    daemon_reload: true
