---
- name: Gather package facts
  package_facts:
    manager: apt

- name: Install packages
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: yes
  when: item not in ansible_facts.packages
  loop: "{{ list }}"
