---
- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: add Elastic's signing key
  ansible.builtin.shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Install apt-transport-https
  ansible.builtin.apt:
    name: apt-transport-https
    update_cache: yes

- name: Add repository definition
  ansible.builtin.shell: echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list

- name: To install OSS Elasticsearch
  ansible.builtin.shell: echo "deb https://artifacts.elastic.co/packages/oss-7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list

- name: Create init lockfile directory
  ansible.builtin.file:
    path: "{{ init_lockfile_path }}"
    state: "directory"

- name: Create Lock file
  ansible.builtin.file:
    path: "{{ init_lockfile_path }}/{{ init_lockfile }}"
    state: touch
